apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: checkpoint-api
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: checkpoint-api
  template:
    metadata:
      labels:
        name: checkpoint-api
    spec:
      serviceAccountName: checkpoint-serviceaccount
      # Note that control plane nodes will not run the pods. (no reason, we can change it in the future)
      containers:
      - name: checkpoint-api
        image: ghcr.io/kennethk-1201/k8s-checkpoint-api:main
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: checkpoints
          mountPath: /checkpoints
        - name: pki
          mountPath: /pki
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: checkpoint-serviceaccount-secret
              key: token
      # it may be desirable to set a high priority class to ensure that a DaemonSet Pod
      # preempts running Pods
      # priorityClassName: important
      terminationGracePeriodSeconds: 30
      volumes:
      - name: checkpoints
        hostPath:
          path: /var/lib/kubelet/checkpoints
      - name: pki
        hostPath:
          path: /etc/kubernetes/pki
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: kube-system
spec:
  serviceAccountName: checkpoint-serviceaccount
  containers:
  - name: busybox
    image: radial/busyboxplus:curl
    command: [ "/bin/sh", "-c", "--" ] # Just spin & wait forever
    args: [ "while true; do sleep 30; done;" ]
    env:
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: TOKEN
        valueFrom:
          secretKeyRef:
            name: checkpoint-serviceaccount-secret
            key: token
    volumeMounts:
      - name: checkpoints
        mountPath: /checkpoints
      - name: pki
        mountPath: /pki
  volumes:
    - name: checkpoints
      hostPath:
        path: /var/lib/kubelet/checkpoints
    - name: pki
      hostPath:
        path: /etc/kubernetes/pki