apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: checkpoint-clusterrole
rules:
- apiGroups:
  - ""
  resources:
  - 'nodes/checkpoint'
  - 'nodes/pods'
  - 'nodes/proxy'
  verbs:
  - 'create'
  - 'get'