apiVersion: v1
kind: Secret
metadata:
  name: checkpoint-serviceaccount-secret
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: checkpoint-serviceaccount
type: kubernetes.io/service-account-token